<h2>Cadastro de Usuarios - Adicionar Cadastro</h2>
<form action="<?=$this->url(array("controller"=>"usuario","action"=>"create"),null,true)?>" method="post">
       
    <fieldset>
        <legend>Dados Pessoais</legend>
         Data de Nascimento:
         <input type="date" name="dt_nascimento" value="" autocomplete ="off"/>
         Nome da Mãe:
         <input type="tel" name="nom_mae" value="" autocomplete ="off"/>
         RG:
         <input type="email" name="num_rg" value="" autocomplete ="off"/>
          CPF:
         <input type="text" name="num_cpf" value="" autocomplete ="off"/>
    </fieldset> 
    <fieldset>
        <legend>Dados do usuario</legend>           
        <dl>
            <dt><label for='nom_usuaurio'>Nome do Usuario</label></dt>
            <dd><input type="text" name="nom_usuario" value="" autocomplete ="off"/></dd>
            <dt><label for='desc_senha'>Senha</label></dt>
            <dd><input type="password" name="desc_senha" value="" autocomplete ="off"/></dd>
        </dl>
        Status:
         <select name="flg_status_usuario">
                 <option value="default" selected>Selecione o Status do Usuario</option>
                 <option value="1">Ativo</option>
                 <option value="0">Inativo</option>
             </select>      
          Tipo Usuario:
         <select name="flg_tipo_usuario">
                 <option value="default" selected>Selecione o Tipo de usuario</option>
                 <option value="A">Aluno</option>
                 <option value="F">Funcionario</option>
                 <option value="P">Professor</option>
             </select>
          Delega Poder:
         <input type="text" name="delega_poder" value="" autocomplete ="off"/>      
          Data de Validade da Senha:
         <input type="date" name="dt_validade_senha" value="" autocomplete ="off"/>
          Data de Validade do Login:
         <input type="date" name="dt_validade_login" value="" autocomplete ="off"/>
    </fieldset>
    <fieldset>
           <legend>Dados Academicos</legend>
           <table>
               <tr>
                   <td> Ra/Matricula:</td>
                   <td><input type="text" name="num_ra_matricula" value="" autocomplete ="off"/></td>
                   <td>Campus</td>
                   <td><input type="text" name="desc_campus" value="" autocomplete ="off"/>  </td>
               </tr>
           </table>               
    </fieldset>
    <fieldset>
        <legend>Contato</legend>
        Telefone:
         <input type="text" name="num_telefone" value="" autocomplete ="off"/>
         Celular:
         <input type="text" name="num_celular" value="" autocomplete ="off"/>
         Email</td>
         <input type="text" name="desc_email" value="" autocomplete ="off"/>
    </fieldset>
   <button type="submit" class="btn btn-primary">Enviar<i class="icon-ok"></i></button>
</form>
<p class="text-right"> <a class="btn btn-primary" href="<?=$this->url(array("controller"=>"usuario","action"=>"index"),null,true)?>">Voltar</a></p>